import { type NextPage } from "next";
import Head from "next/head";
import PostTweet from "../components/PostTweet";
import Timeline from "../components/Timeline";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-start">
        <div className="container flex flex-col items-start justify-center sm:w-[640px]">
          <PostTweet />
          <Timeline />
        </div>
      </main>
    </>
  );
};

export default Home;
